services:
  yt4kids2:
    container_name: yt4kids2
    image: yt4kids2:latest
    # build:
    #   context: .
    restart: always
    environment:
      - DATABASE_URL=postgres://dev:dev@10.22.22.1:5432/dev
      - YT_PORT=3000
      - YK_STORAGE_DIR=./storage
      - YT_ACCESS_SECRET=ASECRETINDEED
      - YT_REFRESH_SECRET=REFRESHINGISGOOD
      - YT_ACCESS_DURATION=1d
      - YT_REFRESH_DURATION=1w
      - YT_DOWNLOAD_INTERVAL=60000
      - YT_DOWNLOAD_RETRIES=3
    ports:
      - "3010:3000"
    volumes:
      - "/disk/2/yt4kids:/app/storage"

    
